### ISSUE TITLE
when the code and data will be released? 

### ISSUE THREAD

**Issue by 2132660698** [carlomarxdk/life2vec-light#1]
I’ve been following it for a long time. Please tell me when the code and data will be released. Thank you!

**Comment by carlomarxdk** [comment]
Hey there,
Thanks for the message. 
I think it will take me one more week (I had a lot of work related stuff in January, so I could not focus on the code) - I hope to finish it by the 10th Feb (meanwhile, the main life2vec repository contains all the code, this repository will have a simplified version). 
Just a note - we won't release the data, instead we are going to provide a randomly generated dataset.

**Comment by 2132660698** [comment]
Thank you very much for your reply, looking forward to seeing your great work and wishing you good health.

**Comment by carlomarxdk** [comment]
UPDATE: I am actively working on the code, hope to release during the weekend!

**Comment by carlomarxdk** [comment]
Still working! But the first batch of code should be online by Wednesday!
